// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const bobby = require('./6-alternative-flavour')
require('./7-mind-gren')
//sayHi('susan')
//sayHi(names.john)
//sayHi(names.peter)
//console.log(bobby)
